name: Build Storybook

on:
  pull_request:
    branches: [dev]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: "20.x"
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          npm ci
          npm run storybook:install
          npm run storybook:build
        env:
          CI: true
