name: Lint Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions: {}

jobs:
  lint-pr:
    name: Lint PR Title
    permissions:
      contents: read
    uses: equinor/ops-actions/.github/workflows/commitlint.yml@bc5f7b87fe7bf2a9d7d4711d190f371e9689127e # 9.39.5
    with:
      message: ${{ github.event.pull_request.title }}