name: Lint Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions: {}

jobs:
  lint-pr:
    name: Lint PR Title
    permissions:
      contents: read
    uses: equinor/ops-actions/.github/workflows/commitlint.yml@e925ef9959a37d43073b77efa2f73c64253fbd55 # 9.37.2
    with:
      message: ${{ github.event.pull_request.title }}