name: Lint Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions: {}

jobs:
  lint-pr:
    name: Lint PR Title
    permissions:
      contents: read
    uses: equinor/ops-actions/.github/workflows/commitlint.yml@af5bad1a47ab8f8c333f8910f06c1938dd962dac # 9.43.0
    with:
      message: ${{ github.event.pull_request.title }}