name: Node CI

on:
  push:
    branches: [dev]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: "20.x"

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm test
          npm run lint
        env:
          CI: true
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@7f8fe47b3bea1be0c3aec2b717c5ec1f3e03410b
        with:
          token: ${{secrets.NPM_TOKEN}}
          provenance: true
