name: Publish to NPM
on:
  workflow_call:
    inputs:
      working_directory:
        description: "The working directory to publish from"
        required: false
        default: "."
        type: string
      package_name:
        description: "The name of the package to publish"
        required: true
        type: string
    secrets:
      npm_token:
        description: "The NPM token to use for publishing"
        required: true

jobs:
  publish:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get published package version
        shell: bash
        run: |
          PKG_VERSION="$(npm search videx-wellog -json true | jq .[].version -r)"
