name: Release

on:
  push:
    branches:
      - dev

permissions: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    env:
      NODE_VERSION: "24.x"
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7
        with:
          release-type: node

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Setup Node ${{ env.NODE_VERSION }}
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: ${{ env.NODE_VERSION }}
          package-manager-cache: false

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci

      - name: Build library
        if: ${{ steps.release.outputs.release_created }}
        run: npm run build --if-present

      - name: Test
        if: ${{ steps.release.outputs.release_created }}
        run: npm test

      - name: Publish to npm
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish

